// <auto-generated />
using KancelarCloud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace KancelarCloud.Migrations
{
    [DbContext(typeof(ContextDBcs))]
    partial class ContextDBcsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KancelarCloud.Models.FileVloj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DeleteFile");

                    b.Property<DateTime>("EnterDate");

                    b.Property<string>("FileName");

                    b.Property<string>("PathFileName");

                    b.Property<int>("SizeFile");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("FileVlojs");
                });

            modelBuilder.Entity("KancelarCloud.Models.Org", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("NameOrg")
                        .IsRequired();

                    b.HasKey("OrgId");

                    b.ToTable("Orgs");
                });
#pragma warning restore 612, 618
        }
    }
}
